import React, { useState } from 'react';
import clsx from 'clsx';
import FormGroup from '@mui/material/FormGroup';
import FormControlLabel from '@mui/material/FormControlLabel';
import Switch, { SwitchProps } from '@mui/material/Switch';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import { styled, TextareaAutosize } from '@mui/material';

import styles from '../../../../css/Marketing.module.css';
import { FaAngleDown } from 'react-icons/fa';

const metaData = [
    {
        value: '0',
        name: 'Autogenerated',
    },
    {
        value: '1',
        name: 'Custom',
    },
];

const metaDataDescription = [
    {
        value: 'A',
        name: 'Autogenerated',
    },
    {
        value: 'C',
        name: 'Custom',
    },
];

const AntSwitch = styled(Switch)(({ theme }) => ({
    width: 28,
    height: 16,
    padding: 0,
    display: 'flex',
    '&:active': {
        '& .MuiSwitch-thumb': {
            width: 15,
        },
        '& .MuiSwitch-switchBase.Mui-checked': {
            transform: 'translateX(9px)',
        },
    },
    '& .MuiSwitch-switchBase': {
        padding: 2,
        '&.Mui-checked': {
            transform: 'translateX(12px)',
            color: '#fff',
            '& + .MuiSwitch-track': {
                opacity: 1,
                backgroundColor: theme?.palette?.mode === 'dark' ? '#177ddc' : '#1890ff',
            },
        },
    },
    '& .MuiSwitch-thumb': {
        boxShadow: '0 2px 4px 0 rgb(0 35 11 / 20%)',
        width: 12,
        height: 12,
        borderRadius: 6,
        transition: theme?.transitions?.create(['width'], {
            duration: 200,
        }),
    },
    '& .MuiSwitch-track': {
        borderRadius: 16 / 2,
        opacity: 1,
        backgroundColor:
            theme?.palette?.mode === 'dark' ? 'rgba(255,255,255,.35)' : 'rgba(0,0,0,.25)',
        boxSizing: 'border-box',
    },
}));

const Marketing = ({ formValues, handleAddFormChange }: any) => {

    const [isActiveMetaTag, setIsActiveMetaTag] = useState(false);
    const [selectedMetaTag, setSelectedMetaTag] = useState('Autogenerated');

    const [isActiveMetaDescription, setIsActiveMetaDescription] = useState(false);
    const [selectedMetaDescription, setSelectedMetaDescription] = useState('Autogenerated');

    const handleActiveMetaTag = () => {
        setIsActiveMetaTag(!isActiveMetaTag);
    }

    const handleActiveMetaDescription = () => {
        setIsActiveMetaDescription(!isActiveMetaDescription);
    }

    const onChangeForm = (fieldName: string, fieldValue?: string | number) => {
        handleAddFormChange(fieldName, fieldValue ?? '');
    }


    return (
        <>
            <div className={clsx(styles.container)}>
                <h1 className={clsx(styles.title)}>Marketing</h1>

                <div className={clsx(styles.wrap)}>
                    <div className='row'>
                        <div className='col l-6'>
                            <div className='row'>
                                <div className='col l-6'>
                                    <span className={clsx(styles.titleInp)}>
                                        Open Grap Meta Tag
                                    </span>
                                </div>
                                <div className='col l-6'>
                                    <div className={clsx(styles.wrapInp)}>
                                        <div className={clsx(styles.dropDown)}>
                                            <button
                                                className={clsx(styles.dropDownBtn)}
                                                onClick={handleActiveMetaTag}
                                            >
                                                {selectedMetaTag}
                                                <span style={{ float: 'right', }}><FaAngleDown /></span>
                                            </button>

                                            {isActiveMetaTag && (
                                                <div className={clsx(styles.dropDownContent)} style={{ height: 'auto' }}>
                                                    {metaData.map((meta: any, index: number) => (
                                                        <div
                                                            key={index}
                                                            className={clsx(styles.dropDownItem)}
                                                            onClick={(e) => {
                                                                setSelectedMetaTag(meta.name);
                                                                setIsActiveMetaTag(false);
                                                                onChangeForm('og_tags_type', meta.value);
                                                            }}
                                                        >
                                                            {meta.name}
                                                        </div>
                                                    ))}
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className='col l-6'></div>
                    </div>

                    {
                        selectedMetaTag === 'Custom' ?
                            (
                                <div className={clsx(styles.wrap)} style={{ margin: '1rem 0' }}>
                                    <div className='row'>
                                        <div className='col l-6'>
                                            <div className='row'>
                                                <div className='col l-6'>
                                                </div>
                                                <div className='col l-6'>
                                                    <div className={clsx(styles.wrapInp)}>
                                                        <div className={clsx(styles.dropDown)}>
                                                            <textarea
                                                                name="og_tags"
                                                                id="og_tags"
                                                                className={clsx(styles.textarea)}
                                                                value={formValues.og_tags}
                                                                onChange={(e) => onChangeForm('og_tags', e.target.value)}
                                                            />
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className='col l-6'></div>
                                    </div>
                                </div>
                            ) : null
                    }
                </div>

                <div className={clsx(styles.wrap)}>
                    <div className='row'>
                        <div className='col l-6'>
                            <div className='row'>
                                <div className='col l-6'>
                                    <span className={clsx(styles.titleInp)}>
                                        Meta Description
                                    </span>
                                </div>
                                <div className='col l-6'>
                                    <div className={clsx(styles.wrapInp)}>
                                        <div className={clsx(styles.dropDown)}>
                                            <button className={clsx(styles.dropDownBtn)} onClick={handleActiveMetaDescription}>
                                                {selectedMetaDescription}
                                                <span style={{ float: 'right', }}><FaAngleDown /></span>
                                            </button>

                                            {isActiveMetaDescription && (
                                                <div className={clsx(styles.dropDownContent)} style={{ height: 'auto' }}>
                                                    {metaDataDescription.map((meta: any, index: number) => (
                                                        <div
                                                            key={index}
                                                            className={clsx(styles.dropDownItem)}
                                                            onClick={() => {
                                                                setSelectedMetaDescription(meta.name);
                                                                setIsActiveMetaDescription(false);
                                                                onChangeForm('meta_desc_type', meta.value);
                                                            }}
                                                        >
                                                            {meta.name}
                                                        </div>
                                                    ))}
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className='col l-6'></div>
                    </div>

                    {
                        selectedMetaDescription === 'Custom' ?
                            (
                                <div className={clsx(styles.wrap)} style={{ margin: '1rem 0' }}>
                                    <div className='row'>
                                        <div className='col l-6'>
                                            <div className='row'>
                                                <div className='col l-6'>
                                                </div>
                                                <div className='col l-6'>
                                                    <div className={clsx(styles.wrapInp)}>
                                                        <div className={clsx(styles.dropDown)}>
                                                            <textarea
                                                                name="meta_description"
                                                                id=""
                                                                className={clsx(styles.textarea)}
                                                                value={formValues.meta_description}
                                                                onChange={(e) => onChangeForm('meta_description', e.target.value)}
                                                            />
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className='col l-6'></div>
                                    </div>
                                </div>
                            ) : null
                    }
                </div>

                <div className={clsx(styles.wrap)}>
                    <div className='row'>
                        <div className='col l-6'>
                            <div className='row'>
                                <div className='col l-6'>
                                    <span className={clsx(styles.titleInp)}>
                                        Meta Keywords
                                    </span>
                                </div>
                                <div className='col l-6'>
                                    <div className={clsx(styles.wrapInp)}>
                                        <input
                                            type="text"
                                            name="meta_keywords"
                                            id=""
                                            className={clsx(styles.inp)}
                                            value={formValues.meta_keywords}
                                            onChange={(e) => onChangeForm('meta_keywords', e.target.value)}
                                        />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className='col l-6'></div>
                    </div>
                </div>

                <div className={clsx(styles.wrap)}>
                    <div className='row'>
                        <div className='col l-6'>
                            <div className='row'>
                                <div className='col l-6'>
                                    <span className={clsx(styles.titleInp)}>
                                        Product page title
                                    </span>
                                </div>
                                <div className='col l-6'>
                                    <div className={clsx(styles.wrapInp)}>
                                        <input
                                            type="text"
                                            name="product_page_title"
                                            id=""
                                            className={clsx(styles.inp)}
                                            value={formValues.product_page_title}
                                            onChange={(e) => onChangeForm('product_page_title', e.target.value)}
                                        />
                                    </div>
                                    <p className={clsx(styles.text)}>Leave blank to use product name as Page Title.</p>
                                </div>
                            </div>
                        </div>
                        <div className='col l-6'></div>
                    </div>
                </div>

                <div className={clsx(styles.wrap)}>
                    <div className='row'>
                        <div className='col l-6'>
                            <div className='row'>
                                <div className='col l-6'>
                                    <span className={clsx(styles.titleInp)}>
                                        Add to Facebook product feed
                                    </span>
                                </div>
                                <div className='col l-6'>
                                    <div className={clsx(styles.wrapInp)}>
                                        <Stack direction="row" spacing={1} alignItems="center">
                                            <Typography sx={{ color: '#fff' }}>No</Typography>
                                            <AntSwitch
                                                name='facebook_marketing_enabled'
                                                defaultChecked={formValues?.facebook_marketing_enabled}
                                                onChange={(e) => onChangeForm('facebook_marketing_enabled', e.target.checked ? 1 : 0)}
                                                inputProps={{ 'aria-label': 'ant design' }}
                                            />
                                            <Typography sx={{ color: '#fff' }}>Yes</Typography>
                                        </Stack>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className='col l-6'></div>
                    </div>
                </div>

                <div className={clsx(styles.wrap)}>
                    <div className='row'>
                        <div className='col l-6'>
                            <div className='row'>
                                <div className='col l-6'>
                                    <span className={clsx(styles.titleInp)}>
                                        Add to Google product feed
                                    </span>
                                </div>
                                <div className='col l-6'>
                                    <div className={clsx(styles.wrapInp)}>
                                        <Stack direction="row" spacing={1} alignItems="center">
                                            <Typography sx={{ color: '#fff' }}>No</Typography>
                                            <AntSwitch
                                                name='google_feed_enabled'
                                                defaultChecked={formValues?.google_feed_enabled}
                                                onChange={(e) => onChangeForm('google_feed_enabled', e.target.checked ? 1 : 0)}
                                                inputProps={{ 'aria-label': 'ant design' }} />
                                            <Typography sx={{ color: '#fff' }}>Yes</Typography>
                                        </Stack>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className='col l-6'></div>
                    </div>
                </div>
            </div>
        </>
    );
};

export default Marketing;